spring.application.name=talentos

# Desabilita autoconfiguracao JPA/DataSource (persistencia manual em memoria)
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

# Implementacao de servico padrao (padrao | auditoria)
app.servico.implementacao=padrao
